# Change everything as you please
# "egr" = green
# "oyelo" = yellow
# "ogl" = gold
# "dre" = red
# "ubl" = blue
# "ldo" = BOLD

helmet: 310
chest: 311
leg: 312
boot: 313
baton: 369
checker: 280

batonname: oglBaton
checkername: oglContraband Checker

onduty: egr You are now on duty!
offduty: egr You are now off duty!
no permissions: dre You do not have permission!
alreadyonduty: ubl You are already onduty!
notonduty: ldo You are not onduty!
dropitemonduty: dre You cannot drop items while onduty!