name: CopOnDuty
main: me.josiah.cod.cod
version: 2.0
description: >
             A plugin which allows you to go on and off duty!
commands:
  onduty:
    description: Go onduty.
  offduty:
    description: Go offduty.
  cod:
    description: Opens up a gui to go onduty!